url: "http://blogs.gundersons.us/sabrina"
name: "The Circus"
title: "The Circus"
description: "Sabrina's Blog"
theme: jekyll-theme-merlot
baseurl: "/sabrina"
show_downloads: "false"
page_excerpts: "true"
